test: Add body-file test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,8 +11,8 @@ defaults:
     shell: bash
 
 jobs:
-  test:
-    name: Test
+  test-comment:
+    name: Test comment
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -29,6 +29,30 @@ jobs:
       - name: Check comment
         run: |
           if [ "${{ steps.get_comment.outputs.latest }}" != "This is a test comment." ]; then
+            echo "error::Expected comment 'This is a test comment.' got '$${{ steps.get_comment.outputs.latest }}'"
+            exit 1
+          fi
+  test-body-file:
+    name: Test body file
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Post comment
+        uses: ./
+        with:
+          behavior: delete_and_new
+          bodyFile: ./github/workflows/test-body-file.txt
+          tag: test-body-file
+      - name: Get comment
+        uses: ./
+        id: get_comment
+        with:
+          behavior: latest
+          tag: test-body-file
+      - name: Check comment
+        run: |
+          if [ "${{ steps.get_comment.outputs.latest }}" != "This is a test body file comment." ]; then
             echo "error::Expected comment 'This is a test comment.' got '$${{ steps.get_comment.outputs.latest }}'"
             exit 1
           fi
